version: '3'

services:

  back-login:
    build: .
    ports:
      - "8888:8000"
    environment:
      DATABASE_NAME: medic-bd
      DATABASE_HOST: db-test-free.cdxsrhofpryf.us-east-1.rds.amazonaws.com
      DATABASE_USER: postgres
      DATABASE_PASSWORD: adminadmin
    command: >
      sh -c "sleep 5s &&
             python manage.py migrate &&
             python manage.py runserver"
